arenablog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('core.urls')),
    path('', include('user.urls')),
    path('signup/', include('marketing.urls')),
    path('siteconfig/', include('siteconfig.urls')),

]

urlpatterns.extend(
    static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT
        )
    )

core/urls.py
from django.urls import path
from core.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('feed/', login_required(HomeView.as_view()), name='home_feed_view'),

    # follow and unfollow view
    path('follow/done/', login_required(FollowDoneView.as_view()), name='follow_done_view'),
    path('unfollow/done/', login_required(UnfollowDoneView.as_view()), name='unfollow_done_view'),

    # post related urls
    path('search/blog/', search_blog, name='search_blog'),
    path('search/users/', AllProfilesView.as_view(), name='search_users'),
    path('post/<int:id>/', login_required(PostDetailView.as_view()), name='post_detail_view'),
    path('post/create/', login_required(PostCreateView.as_view()), name='post_create_view'),
    path('post/update/<int:id>/', login_required(PostUpdateView.as_view()), name='post_update_view'),
    path('post/delete/<int:id>/', login_required(PostDeleteView.as_view()), name='post_delete_view'),
    path('post/save/<int:id>/', login_required(PostSaveView.as_view()), name='post_save_view'),
    path('post/unsave/<int:id>/', login_required(PostUnsaveView.as_view()), name='post_unsave_view'),
    
    path('post/liked/', login_required(LikedPostsView.as_view()), name='liked_posts_view'),
    path('post/saved/', login_required(SavedPostsView.as_view()), name='saved_posts_view'),
    path('post/explore/', login_required(ExplorePostsView.as_view()), name='explore_posts_view'),
    path('<slug:category_slug>/',category, name='category'),
    path('post/categories/page/', categorypage, name='category_page'),

    path('post/like/<int:id>/', PostLikeView.as_view(), name='post_like_view'),
    path('post/unlike/<int:id>/', PostUnlikeView.as_view(), name='post_unlike_view'),
    path('post/comment/<int:id>/', PostCommentView.as_view(), name='post_comment_view'),
]

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

from core.utils import auto_save_current_user
# Create your models here.

User = get_user_model()


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Category(models.Model):
    title = models.CharField(max_length=20)
    category_image=models.ImageField(upload_to='category/images/',default='logo/logo.png')
    slug=models.SlugField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural='Post Categories'

# Posts Model
class Post(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)  # null == None, blank = ''
    image = models.ImageField(upload_to='post_images')   # BASE_DIR -> media -> post_images
    user = models.ForeignKey(User, on_delete=models.PROTECT, editable=False,related_name='posts')    # user_id
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    categories = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='posts')
    featured = models.BooleanField(blank=True, null=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Post, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('post_detail_view', kwargs={
            'id': self.id
        })

    def get_update_url(self):
        return reverse('post-update', kwargs={
            'pk': self.pk
        })

    def get_delete_url(self):
        return reverse('post_delete_view', kwargs={
            'pk': self.pk
        })


    @property
    def likes_count(self):
        count = self.like.count()
        return count

    @property
    def comments_count(self):
        count = self.comment_set.count()
        return count

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

# Comments Model
class Comment(models.Model):
    text = models.CharField(max_length=240)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    commented_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text


# Likes Model
class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='like')
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    liked_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post.id)



# Followers Model
class Follow(models.Model):
    user = models.ForeignKey(User, related_name='follow_follower', on_delete=models.CASCADE, editable=False)
    followed = models.ForeignKey(User, related_name='follow_followed', on_delete=models.CASCADE)
    followed_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.user} --> {self.followed}"


class SavedPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    saved_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post.pk)

core/forms.py
from django import forms
from core.models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','overview','content','categories','featured','image')
        widgets = {
            'text': forms.TextInput(attrs={
                    'class': 'form-control form-control-sm',
                    'placeholder': 'Caption this...'
                }
            )
        }

core/views.py
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import *
from django.db.models import Count, Q
import sys
from core.models import *
from core.forms import PostCreateForm
from marketing.forms import EmailSignupForm
from marketing.models import Signup

User = get_user_model()


# Create your views here.

#search blog

def search_blog(request):
    queryset = Post.objects.all()
    query = request.GET.get('search')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(overview__icontains=query)
        ).distinct()
    context = {
        'queryset': queryset
    }
    return render(request, 'search_blog.html', context)

#search users
class AllProfilesView(LoginRequiredMixin,View):
    template_name = 'user/all_profiles.html'

    def get(self, request, *args, **kwargs):
        search_term = request.GET.get('query')

        if search_term:
            all_profiles = User.objects.filter(
                    Q(username__contains=search_term) | Q(full_name__contains=search_term)
                ).exclude(
                    username=request.user.username
                )
        else:
            all_profiles = User.objects.none()

        context = {'all_profiles': all_profiles}
        return render(request, self.template_name, context=context)

def is_users(post_user, logged_user):
    return post_user == logged_user


class HomeView(LoginRequiredMixin, ListView):
    model = Post
    form_class = EmailSignupForm
    template_name = 'core/feed.html'
    context_object_name = 'all_posts'
    ordering = ['-created_on']
    paginate_by = 3

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        all_users = []
        data_counter = Post.objects.values('user').annotate(author_count=Count('user')).order_by('-author_count')[:6]

        featured = Post.objects.filter(featured=True)
        latest = Post.objects.order_by('-created_on')[0:3]

        for aux in data_counter:


            all_users.append(User.objects.filter(pk=aux['user']).order_by('-posts__created_on').first())
        data['all_users'] = all_users[:5]
        data['featured'] = featured[:3]
        data['latest'] = latest[:3]
        print(all_users, file=sys.stderr)
        return data

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        new_signup = Signup()
        new_signup.email = email
        new_signup.save()
        messages.info(request, "Successfully subscribed")
        return redirect("home_feed_view")

    def get_queryset(self):
        user = self.request.user
        qs = Follow.objects.filter(user=user)
        follows = [user]
        for obj in qs:
            follows.append(obj.followed)
        return Post.objects.filter(user__in=follows).order_by('-created_on')



class PostDetailView(View):
    template_name = 'core/post_detail.html'

    def get(self, request, *args, **kwargs):
        post_id = kwargs.get('id')

        try:
            post_obj = Post.objects.get(pk=post_id)
            if self.request.user.is_authenticated:
                PostView.objects.get_or_create(
                    user=self.request.user,
                    post=post_obj
                )
        except Exception as e:
            return redirect(request.META.get('HTTP_REFERER'))

        try:
            Like.objects.get(user=request.user, post_id=post_id)
            liked_this_post = True
        except Exception as e:
            liked_this_post = False

        try:
            SavedPost.objects.get(user=request.user, post_id=post_id)
            post_saved = True
        except Exception as e:
            post_saved = False

        context = {
            'post': post_obj,
            'liked_this_post': liked_this_post,
            'post_saved': post_saved,
        }

        return render(request, self.template_name, context=context)

class PostCreateView(CreateView):
    model = Post
    template_name = 'core/post_new.html'
    form_class = PostCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create a new post or article'
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return redirect(reverse("post_detail_view", kwargs={
            'id': form.instance.pk
        }))

class PostUpdateView(UpdateView):
    model = Post
    template_name = 'core/post_new.html'
    form_class = PostCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update this post'
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return redirect(reverse("post_detail_view", kwargs={
            'id': form.instance.pk
        }))

class PostDeleteView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')
        try:
            post_obj = Post.objects.get(pk=post_id)
        except Exception as e:
            pass
        if request.user == post_obj.user:
            post_obj.delete()

        return redirect(request.META.get('HTTP_REFERER'))


class PostSaveView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')

        try:
            post_obj = Post.objects.get(pk=post_id)
        except Exception as e:
            pass

        try:
            SavedPost.objects.create(post_id=post_id, user=self.request.user)
        except Exception as e:
            pass

        return redirect(request.META.get('HTTP_REFERER'))


class PostUnsaveView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')

        try:
            savedpost_obj = SavedPost.objects.get(post_id=post_id)
            savedpost_obj.delete()
        except Exception as e:
            pass

        return redirect(request.META.get('HTTP_REFERER'))


class PostLikeView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')

        try:
            Like.objects.get(post_id=post_id, user=self.request.user)
        except Exception as e:
            Like.objects.create(post_id=post_id, user=self.request.user)

        return redirect(request.META.get('HTTP_REFERER'))


class PostUnlikeView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')
        try:
            like_obj = Like.objects.get(post_id=post_id, user=self.request.user)
            like_obj.delete()
        except Exception as e:
            pass

        return redirect(request.META.get('HTTP_REFERER'))


class PostCommentView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')
        comment_text = request.POST.get('comment_text')

        Comment.objects.create(post_id=post_id, text=comment_text, user=self.request.user)

        return redirect(request.META.get('HTTP_REFERER'))


class FollowDoneView(View):
    def visible_user(self):
        return get_object_or_404(User, username=self.kwargs.get('followed_user_id'))

    def post(self, request, *args, **kwargs):
        followed_user_id = request.POST.get('followed_user_id')
        followed_user_obj = User.objects.get(pk=followed_user_id)

        try:
            Follow.objects.get(user=request.user, followed=self.visible_user())
        except Exception as e:
            follow_obj = Follow.objects.create(user=request.user, followed=followed_user_obj)

        return redirect(request.META.get('HTTP_REFERER'))


class UnfollowDoneView(View):
    def post(self, request, *args, **kwargs):
        unfollowed_user_id = request.POST.get('unfollowed_user_id')
        unfollowed_user_obj = User.objects.get(pk=unfollowed_user_id)

        try:
            follow_obj = Follow.objects.get(user=self.request.user, followed=unfollowed_user_obj)
            follow_obj.delete()
        except Exception as e:
            pass

        return redirect(request.META.get('HTTP_REFERER'))


class LikedPostsView(View):
    template_name = 'core/liked_posts.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class SavedPostsView(View):
    template_name = 'core/saved_posts.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class ExplorePostsView(View):
    template_name = 'core/posts_explore.html'

    def get(self, request, *args, **kwargs):
        all_posts = Post.objects.annotate(count=Count('like')).order_by('-count')
        context = {'all_posts': all_posts}
        return render(request, self.template_name, context=context)

def category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)

    return render(request, 'core/all_post_categories.html', {'category': category})


def categorypage(request):
    return render(request, 'core/all_post_categories.html')

templates/core/all_post_categories.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/user/all_profiles.css' %}">
{% endblock %}

{% block content %}
<div class="container py-5">
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>
        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">
            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                {% for category in categories %}
                <li class="nav-item">
                    <a href="{% url 'category' category.slug %}" class="nav-link waves-effect">
                        <img src="{{ category.category_image.url }}" class="profile__pic" width="100%"
                             style="border-radius:50%;">
                        <strong>{{category.title}}</strong></a>
                    <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
    </nav>
    <div class="row">
        <div class="card-header">
            <h3 class="m-0" style="color: #5f5f5f;">{{tag_line}}</h3>
        </div>
        <div class="col-12 col-md-8 card offset-md-2">
            <!-- All categories -->
            <h1 style="color:black;">{{category}}</h1>
            {% for post in category.post_set.all %}
            <!-- Single category Row -->
            <a href="{{post.get_absolute_url}}" class="text-decoration-none">
                <div class="row py-3 px-5 border-bottom">
                    <!-- post picture -->
                    {% if post.image %}
                    <img src="/media/{{ user.picture }}" class="rounded-circle z-depth-0 profile__pic" width="100%">
                    {% else %}
                    <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"
                         class="profile__pic rounded-circle z-depth-0" width="50%">
                    {% endif %}
                    <!-- post picture end -->
                    <div class="d-flex mx-4">
                        <!--  post title -->
                        <p class="m-auto" style="color:blue;"><a href="{{post.get_absolute_url}}">{{ post.title }}</a>
                        </p>
                    </div>
                    <div class="ml-auto">
                        <button class="btn btn-sm btn-primary mx-2" type="submit">
                            <a href="{{post.get_absolute_url}}">view post</a>
                        </button>
                    </div>
                </div>
            </a>
            <!-- Single post Row end -->
            {% endfor %}
            <!-- All User Profiles end -->
        </div>
    </div>
</div>
{% endblock %}

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/core/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/core/navbar.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" type="image/png" href="{% static 'blog/logo.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.11.2/css/all.css"
          integrity="sha384-zrnmn8R8KkWl12rAZFt4yKjxplaDaT7/EUkKm7AovijfrQItFWR7O/JJn4DAa/gx" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">

    {% block extra_head %}{% endblock %}

    <title>kimfitty</title>
</head>
<body style="background: -webkit-linear-gradient(45deg, #f09933 25%,#e6983c 0%,#dc2743 25%,#cc2366 60%,#bc1888 65%); ">

{% include 'components/navbar.html' %}

<section>
    {% block content %}{% endblock %}
</section>
{% include 'footer.html' %}
{% include 'scripts.html' %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
{% block extra_body %}{% endblock %}

</body>
</html>

templates/core/liked_posts.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="container my-5">
        <div class="row justify-content-center">

            <!-- All Liked Posts -->
            {% for like_obj in request.user.like_set.all %}
                {% with post=like_obj.post %}

                <!-- Single Posts Grid -->
                <div class='col-12 col-md-4 col-lg-3 my-4 mx-3 px-0 card'>
                    <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">

                        <!-- Post Image -->
                        <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">

                        <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                            <span class="mx-2">
                                <span class="far fa-heart"></span>

                                <!-- total likes -->
                                {{ post.likes_count }}

                            </span> 
                            <span class="mx-2">
                                <span class="far fa-comment"></span>

                                <!-- total comments -->
                                {{ post.comments_count }}
                                
                            </span>
                        </div>
                    </a>
                </div>
                <!-- Single Posts Grid end -->

                {% endwith %}
            {% endfor %}
            <!-- All Liked Posts end -->

        </div>
    </div>

{% endblock %}

templates/core/post_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/core/post_card.css' %}">
{% endblock %}

{% block content %}

    <div class="container my-5">
        <div class="row">
            <div class="col-12">
                <!-- Single Posts in Detail Card -->
                {% include 'components/post_detail_card.html' %}
            </div>
        </div>
    </div>

{% endblock %}

templates/core/post_new.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-4 offset-4 mb-5 mt-5">
<h3>{{ title }} an article</h3>
{{ form.media }}
<form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">{% if title == 'Update this post' %}Update{% else %}Post{% endif %}</button>
</form>
</div>
{% endblock content %}

templates/core/posts_explore.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="container my-5">
        <div class="row justify-content-center">

            <!-- All posts ordered by number of likes -->
            {% for post in all_posts %}
                <!-- Single post grid -->
                <div class='col-12 col-md-4 col-lg-3 my-4 mx-3 px-0 card'>
                    <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">

                        <!-- Post Image -->
                        <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">

                        <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                            <span class="mx-2">
                                <span class="far fa-heart"></span>

                                <!-- Total likes -->
                                {{ post.likes_count }}

                            </span> 
                            <span class="mx-2">
                                <span class="far fa-comment"></span>

                                <!-- Total comments -->
                                {{ post.comments_count }}

                            </span>
                        </div>
                    </a>
                </div>
                <!-- Single post grid end -->

            {% endfor %}
            <!-- All posts ordered by number of likes end -->

        </div>
    </div>

{% endblock %}

templates/core/saved_posts.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="container my-5">
        <div class="row justify-content-center">

            <!-- All Saved Posts -->
            {% for savedpost_obj in request.user.savedpost_set.all %}
                {% with post=savedpost_obj.post %}

                <!-- Single Posts Grid -->
                <div class='col-12 col-md-4 col-lg-3 my-4 mx-3 px-0 card'>
                    <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">

                        <!-- Post image -->
                        <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">
                        
                        <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                            <span class="mx-2">
                                <span class="far fa-heart"></span>

                                <!-- Total likes -->
                                {{ post.likes_count }}

                            </span> 
                            <span class="mx-2">
                                <span class="far fa-comment"></span>

                                <!-- Total comments -->
                                {{ post.comments_count }}

                            </span>
                        </div>
                    </a>
                </div>
                <!-- Single Posts Grid end -->

                {% endwith %}
            {% endfor %}
            <!-- All Saved Posts end -->

        </div>
    </div>

{% endblock %}